-- =============================================================
-- 002 — Seed Quiz 1: Mapei Ceramic Line Product Knowledge
--
-- 30 questions imported from supabase/seeds/mapei_quiz_1.json
-- Total max_score: 57 (10×1 + 11×2 + 5×3 + 4×4)
-- Idempotent — re-runs replace the seed quiz cleanly.
-- =============================================================

-- Drop and recreate the seed quiz so re-runs are clean.
DELETE FROM quizzes WHERE title = 'Mapei Ceramic Line — Product Knowledge';

WITH q AS (
  INSERT INTO quizzes (title, week_number, is_unlocked, max_score)
  VALUES ('Mapei Ceramic Line — Product Knowledge', 1, FALSE, 57)
  RETURNING id
)
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, difficulty, points, order_index) VALUES
((SELECT id FROM q), 'Which Mapei product is a two-component adhesive that uses a latex liquid instead of water?', 'Keraflex', 'Granirapid', 'Adesilex P9', 'Kerabond Plus', 'B', 'Granirapid is a two-component system — Part A powder is mixed directly into Part B latex; no water is added.', 'Master / Mix Prep', 'very_easy', 1, 0),
((SELECT id FROM q), 'What colour options does Adesilex P7 come in?', 'White only', 'Grey only', 'White or Grey', '16 colours', 'B', 'Adesilex P7 is the only standard cementitious adhesive in the Mapei ceramic line offered in grey only — no white version.', 'Master', 'very_easy', 1, 1),
((SELECT id FROM q), 'What is the bag size of the Ultralite S2 adhesive?', '15 kg', '20 kg', '25 kg', '30.5 kg', 'A', 'All three Ultralite products (S1, S2, S2 Quick) come in 15 kg lightweight bags — same volume as a conventional 25 kg bag.', 'Master', 'very_easy', 1, 2),
((SELECT id FROM q), 'Keracolor FF is which type of product?', 'Tile adhesive', 'Cementitious grout', 'Silicone sealant', 'Epoxy adhesive', 'B', 'Keracolor FF is a polymer-modified cementitious grout (CG2WA) for joints up to 6 mm — it fills tile joints, it does not bond tiles.', 'Master / Distinctions', 'very_easy', 1, 3),
((SELECT id FROM q), 'Mapesil AC is supplied in what packaging?', '15 kg bag', '25 kg bag', '10 kg kit', '310 ml cartridge', 'D', 'Mapesil AC is a one-component silicone sealant supplied in 310 ml cartridges — applied with a standard caulking gun.', 'Master', 'very_easy', 1, 4),
((SELECT id FROM q), 'How many colours is Mapesil AC available in (excluding transparent)?', '10', '16', '17', '40', 'D', 'Mapesil AC is available in 40 colours plus transparent — the largest colour palette in the entire Mapei ceramic line.', 'Master / Distinctions', 'very_easy', 1, 5),
((SELECT id FROM q), 'Keralastic and Keralastic T are what kind of adhesive?', 'Cementitious', 'Two-component polyurethane', 'Acrylic dispersion', 'Epoxy resin', 'B', 'Both are two-component reaction-resin (R2 / R2T) polyurethane adhesives — no water, no cement, classified per EN 12004 as R2.', 'Master', 'very_easy', 1, 6),
((SELECT id FROM q), 'Kerapoxy is a two-component epoxy product. What does it function as?', 'Grout only', 'Adhesive only', 'Both grout and adhesive', 'Sealant', 'C', 'Kerapoxy is dual-classified — RG (reaction-resin grout per EN 13888) and R2T (reaction-resin adhesive per EN 12004). It can be used as either.', 'Master / Distinctions', 'very_easy', 1, 7),
((SELECT id FROM q), 'Mapesil Z Plus is specifically formulated for which application area?', 'Façades', 'Pedestrian walkways', 'Sanitary fittings (baths, showers, saunas)', 'Pool expansion joints', 'C', 'Mapesil Z Plus is a mould-resistant acetic silicone designed for bathrooms, showers, saunas, kitchens — sanitary fittings. Not for pool expansion joints (use Mapesil AC for those).', 'Distinctions', 'very_easy', 1, 8),
((SELECT id FROM q), 'What does the letter ''F'' stand for in a Mapei adhesive classification code (e.g. C2F)?', 'Flexible', 'Fast-setting', 'Floor-only', 'Fibre-reinforced', 'B', 'F = fast-setting / rapid-hardening per ISO 13007 / EN 12004. Granirapid (C2F S1) and Ultralite S2 Quick (C2FE S2) carry the F.', 'Code Decoder', 'very_easy', 1, 9),
((SELECT id FROM q), 'What is the pot life of Granirapid once mixed?', '20 minutes', '45 minutes', '2 hours', 'more than 8 hours', 'B', 'Granirapid is fast-setting — pot life 45 min. The other options are real pot lives of other Mapei products (Mapesil skin time, Keracolor FF, standard C2 adhesives).', 'Timing', 'easy', 2, 10),
((SELECT id FROM q), 'What does the ''S2'' classification mean in C2E S2?', 'Slip-resistant level 2', 'Highly deformable (≥ 5 mm)', 'Two-component', 'Sanded grout', 'B', 'S2 = highly deformable per EN 12004 (transversal deformation ≥ 5 mm). S1 = deformable (≥ 2.5 mm and < 5 mm). T (not S) means slip-resistant.', 'Code Decoder', 'easy', 2, 11),
((SELECT id FROM q), 'How long after installation can a swimming pool tiled with Granirapid be filled with water?', '24 hours', '3 days', '7 days', '21 days', 'B', 'Granirapid is fast-setting — pools fillable after 3 days. Most standard cementitious adhesives need 21 days; Kerapoxy needs 10; Keracolor FF as grout needs 7.', 'Timing', 'easy', 2, 12),
((SELECT id FROM q), 'What is the open time of Adesilex P7?', '10 minutes', '20 minutes', '30 minutes', '60 minutes', 'B', 'Adesilex P7 has NO ''E'' in its code (just C2T) — open time only 20 min. The ''E'' adhesives (Keraflex, Kerabond Plus, etc.) have >30 min.', 'Timing / Distinctions', 'easy', 2, 13),
((SELECT id FROM q), 'Mapesil LM is a NEUTRAL silicone. What does that primarily mean for the user?', 'It cures faster than acetic silicones', 'It does not release acetic acid, so it''s safe on marble and acid-sensitive stone', 'It contains no colour pigments', 'It can only be used indoors', 'B', 'Acetic silicones (AC, Z Plus) release acetic acid during cure, which etches limestone, marble and natural stone. Mapesil LM is neutral-curing and ASTM C1248 non-staining — designed for stone.', 'Distinctions', 'easy', 2, 14),
((SELECT id FROM q), 'What is the application temperature range of Granirapid?', '+5 °C to +35 °C', '+5 °C to +40 °C', '+10 °C to +30 °C', '+12 °C to +30 °C', 'B', 'Granirapid: +5 to +40 °C — standard range for cementitious adhesives. +5 to +35 is Ultralite S2 only. +10 to +30 is Keralastic. +12 to +30 is Kerapoxy (narrowest).', 'Master', 'easy', 2, 15),
((SELECT id FROM q), 'What is the shelf-life (storage) of Keralastic and Kerapoxy?', '12 months', '18 months', '24 months', '36 months', 'C', 'Reaction-resin products (Keralastic, Keralastic T, Kerapoxy, Kerapoxy Adhesive) all store 24 months. Cementitious adhesives store 12 months. Mapesil LM and Z Plus store 18 months.', 'Master', 'easy', 2, 16),
((SELECT id FROM q), 'What is the 28-day initial adhesion strength of Granirapid (per EN 1348)?', '1.0 N/mm²', '1.4 N/mm²', '2.0 N/mm²', '2.5 N/mm²', 'D', 'Granirapid achieves 2.5 N/mm² at 28 days — same as Ultralite S2 and S2 Quick. 1.0 is Mapeset (basic), 1.4 is Adesilex P7 / Kerabond T, 2.0 is Keraflex Maxi S1 Zero / Ultralite S1.', 'Performance', 'easy', 2, 17),
((SELECT id FROM q), 'What does the ''W'' stand for in Keracolor FF''s CG2WA classification?', 'White-pigmented', 'Reduced water absorption (water-repellent)', 'Wall-only', 'Waterproof', 'B', 'W = grout with reduced water absorption (DropEffect® water-repellent technology). A = high abrasion resistance. CG2 = improved cementitious grout per EN 13888.', 'Code Decoder', 'easy', 2, 18),
((SELECT id FROM q), 'What is the maximum joint width Keracolor FF can fill?', '3 mm', '6 mm', '10 mm', '15 mm', 'B', 'Keracolor FF (the ''FF'' = Fugolastic Fine / fine joints) is rated for joints up to 6 mm. For wider joints Mapei has other grouts (e.g. Ultracolor Plus).', 'Distinctions', 'easy', 2, 19),
((SELECT id FROM q), 'Which Mapei product features ''Low Dust'' technology to reduce airborne dust during mixing?', 'Granirapid', 'Keraflex Maxi S1 Zero', 'Ultralite S1', 'Adesilex P9', 'C', 'Ultralite S1 has Mapei''s Low Dust technology — its main selling point alongside ~60% higher yield vs conventional Mapei cementitious adhesives.', 'Distinctions', 'easy', 2, 20),
((SELECT id FROM q), 'A customer is renovating a bathroom and wants to install large 60×120 cm porcelain tiles on a wall over an OLD ceramic tile floor that they don''t want to remove. Which adhesive do you recommend?', 'Mapeset (basic, economical)', 'Adesilex P7 (slip-resistant, grey)', 'Ultralite S2 (lightweight, S2 highly deformable, ideal for thin/large porcelain)', 'Kerabond T (basic C1)', 'C', 'Tile-on-tile + large-format porcelain on a wall = needs (a) tile-on-tile capability, (b) high deformability, (c) slip-resistance for vertical, (d) lightweight for ease. Ultralite S2 ticks all four. Mapeset and Kerabond T cap at 900 cm² for tile-on-tile and aren''t deformable enough for large porcelain.', 'Where to Use / Distinctions', 'practical', 3, 21),
((SELECT id FROM q), 'A customer says: ''I''m building an outdoor swimming pool and need to fill it as fast as possible after tiling — what adhesive should I use?''', 'Keraflex (21 days before filling)', 'Adesilex P9 (21 days before filling)', 'Granirapid (3 days before filling)', 'Keraflex Maxi S1 Zero (21 days before filling)', 'C', 'Granirapid is fast-setting and explicitly rated for pools fillable after 3 days. All standard C2TE adhesives need 21 days. Note: for pools with very sensitive natural stone the answer would change to Keralastic.', 'Timing / Where to Use', 'practical', 3, 22),
((SELECT id FROM q), 'A homeowner is sealing the joint between a marble vanity top and the wall. Which sealant should you recommend, and why?', 'Mapesil AC — biggest colour range available', 'Mapesil Z Plus — designed for sanitary fittings', 'Mapesil LM — neutral cure, won''t stain or etch the marble', 'Kerapoxy — most chemically resistant', 'C', 'Acetic silicones (AC, Z Plus) release acetic acid that etches marble and stains acid-sensitive stones. Mapesil LM is neutral-curing and ASTM C1248 non-staining — the only correct choice for marble. Kerapoxy is a grout/adhesive, not a sealant.', 'Distinctions', 'practical', 3, 23),
((SELECT id FROM q), 'A restaurant client needs grout for a busy commercial kitchen — they need it acid-resistant, food-industry compliant, and easy to clean. What do you recommend?', 'Keracolor FF (cementitious, water-repellent)', 'Kerapoxy (epoxy grout, HACCP compliant)', 'Mapesil AC (silicone sealant)', 'Adesilex P9 (improved adhesive)', 'B', 'Kerapoxy is HACCP-compliant per EC Reg. 852/2004 — explicitly designed for dairies, abattoirs, breweries, food-industry environments. It''s acid-resistant for most acids and easy to clean. Keracolor FF is only acid-resistant if pH > 3 and is not HACCP-rated.', 'Distinctions', 'practical', 3, 24),
((SELECT id FROM q), 'A contractor needs to bond ceramic tiles onto a metal substrate — which is the only suitable Mapei product from this set?', 'Granirapid (fast-setting cementitious)', 'Keraflex (high-performance C2TE)', 'Keralastic / Keralastic T (two-component polyurethane)', 'Kerapoxy Adhesive (two-component epoxy)', 'C', 'Every cementitious adhesive in this set explicitly forbids metal. Keralastic/Keralastic T are reaction-resin polyurethanes specifically designed to bond to metal, wood, PVC, rubber, asphalt, and fibre-cement. Kerapoxy Adhesive can also bond metal but the rust must first be removed by sand-blasting — Keralastic is the cleaner, primary recommendation.', 'Where NOT to Use / Distinctions', 'practical', 3, 25),
((SELECT id FROM q), 'A customer mixes Kerabond T with Isolastic latex INSTEAD of water. What is the resulting classification?', 'Stays C1T', 'Becomes C2E', 'Becomes C2ES1', 'Becomes C2ES2', 'D', 'This is the classic upgrade trick: Kerabond T (C1T) + Isolastic neat = C2ES2 (highly deformable improved). Kerabond Plus (C2E) gets a different upgrade — 1:1 Isolastic:water → C2ES1; neat Isolastic → C2ES2.', 'Distinctions', 'medium', 4, 26),
((SELECT id FROM q), 'Which Mapei product has the LONGEST adjustment time in the entire workbook — useful when installing complex tile patterns that need repositioning?', 'Keralastic / Keralastic T (90 min)', 'Kerapoxy Adhesive (130 min)', 'Keraflex (~60 min)', 'Granirapid (3 hours)', 'B', 'Kerapoxy Adhesive has 130 minutes of adjustment time — longest in the set. Keralastic T comes second at 90 min. Granirapid''s ''3-4 h'' is light foot traffic time, not adjustment time (its adjustment is ~3 h).', 'Timing / Distinctions', 'medium', 4, 27),
((SELECT id FROM q), 'For Keraflex (one-component cementitious), how does the water requirement differ between the GREY and WHITE versions per 25 kg bag?', 'Grey and white use the same water amount', 'Grey uses MORE water than white', 'White uses MORE water than grey (9.0–9.5 L vs 7.5–8.0 L)', 'White cannot be mixed with water — only with Isolastic', 'C', 'Keraflex white needs 9.0–9.5 L of water per 25 kg bag vs 7.5–8.0 L for grey. Adesilex P9 is the same way. This is OPPOSITE to Mapeset and Kerabond T (where white uses less water). Common trick question — most assume grey/white are identical.', 'Mix Prep / Distinctions', 'medium', 4, 28),
((SELECT id FROM q), 'Which silicone sealant has the LOWEST movement-capability rating, making it the LEAST flexible of the three?', 'Mapesil AC (±25%)', 'Mapesil LM (±25%)', 'Mapesil Z Plus (±12.5%)', 'All three are rated equally at ±25%', 'C', 'Mapesil Z Plus is rated only ±12.5% movement — half that of AC and LM. This is why Z Plus is restricted to sanitary fittings (low movement) and explicitly NOT recommended for pool expansion joints — use Mapesil AC for high-movement joints.', 'Distinctions', 'medium', 4, 29);

